#library "ObjectiveInternals"
#include "zcommon.acs"

int objectiveInt = 0;

script "objint" (int thisnumber)
{
	objectiveInt = thisnumber;
}

script "Actually Get The Objective" (void)
{
	int returnValue = objectiveInt;
	SetResultValue(returnValue);
}

bool ifCustomObjective = False;
bool ifGenericObjective = True;

script "Enable Custom Objective" (void)
{
	ifCustomObjective = True;
}

script "Disable Custom Objective" (void)
{
	ifCustomObjective = False;
}

script "Enable Generic Objective" (void)
{
	ifGenericObjective = True;
}

script "Disable Generic Objective" (void)
{
	ifGenericObjective = False;
}

script "Set Custom Objective" (int customObj)
{
	if(ifCustomObjective == False) ifCustomObjective = True;
	SetCVarString("whatIsTheCustomObjective", customObj);
}

int objectiveState = 0;

script "Get Objective State" (void)
{
	objectiveState = 0;
	if(ifCustomObjective) objectiveState++;
	if(!ifGenericObjective) objectiveState++;
	Print(i:objectiveState);
	SetResultValue(objectiveState);
}